# Eris service definition for openblockchain
# Start it with `$ eris services start obc --env OPENCHAIN_PEER_ID=vpX` where X
# is the integer enumerating the nodes.
# To set up a testnet add the environment variable to all secondary nodes
# `OPENCHAIN_PEER_DISCOVERY_ROOTNODE=<IP_of_root_node>:30303`.
# For additional information see the open blockchain [setup guide](https://github.com/openblockchain/obc-docs/blob/master/dev-setup/devnet-setup.md).

# Note that the default open blockchain comes with no consensus engine (NOOPS)
# Reference to the [setup guide](https://github.com/openblockchain/obc-docs/blob/master/dev-setup/devnet-setup.md#using-consensus-plugin)
# to follow the instructions needed.

# For more information on configurations, see the services specification:
# https://docs.erisindustries.com/documentation/eris-cli/latest/services_specification/

# These fields marshal roughly into the `$ docker run` command, see:
# https://docs.docker.com/engine/reference/run/

# This is a TOML config file.
# For more information, see https://github.com/toml-lang/toml

name           = "obc"

[service]
image          = "quay.io/eris/obc"
data_container = true
ports          = [ "4243:4243", "30303:30303" ]
volumes        = [  ]
environment    = [
  "OPENCHAIN_VM_ENDPOINT=http://172.17.0.1:4243",
  "OPENCHAIN_PEER_ADDRESSAUTODETECT=true",
]

[maintainer]
name = "Eris Industries"
email = "support@erisindustries.com"

[location]
dockerfile = "https://github.com/eris-ltd/common/blob/master/docker/openblockchain/Dockerfile"
repository = "https://github.com/openblockchain/obc-peer"
website = "https://www.hyperledger.org/"
