# Eris service definition for openblockchain
# Start it with `$ eris services start obc`
# To set up a local testnet ensure `obcmaster` is running first
# Every node needs a unique OPENCHAIN_PEER_ID of the form vpX,
# where X is the integer from 0 to N-1 when using the proof-of-stake
# consensus engine. Please copy and edit this file and register it as a service.

# For more information on configurations, see the services specification:
# https://docs.erisindustries.com/documentation/eris-cli/latest/services_specification/

# These fields marshal roughly into the `$ docker run` command, see:
# https://docs.docker.com/engine/reference/run/

# This is a TOML config file.
# For more information, see https://github.com/toml-lang/toml

name           = "obc"

[service]
image          = "quay.io/eris/obc"
data_container = true
ports          = [ "4243:4243", "30303:30303" ]
volumes        = [  ]
environment    = [
  "OPENCHAIN_VM_ENDPOINT=http://172.17.0.1:4243",
  "OPENCHAIN_PEER_ID=vp$NN"
  "OPENCHAIN_PEER_ADDRESSAUTODETECT=true",
  "OPENCHAIN_PEER_DISCOVERY_ROOTNODE=$ROOTNODE:30303"
]

[maintainer]
name = "Eris Industries"
email = "support@erisindustries.com"

[location]
dockerfile = "https://github.com/eris-ltd/common/blob/master/docker/openblockchain/Dockerfile"
repository = "https://github.com/openblockchain/obc-peer"
website = "https://www.hyperledger.org/"
